data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    num_workers: 2
    num_classes: 6
    
    train_data_root: /content/demo/train/images
    train_label_data_root: /content/demo/train/labels
    val_data_root: /content/demo/test/images
    val_label_data_root: /content/demo/test/labels
    test_data_root: /content/demo/test/images
    test_label_data_root: /content/demo/test/labels

    means: [133.00823618746747, 135.26216656497104, 138.9087738608626]
    stds: [75.08977582295124, 76.59657858929522, 80.89887355601404]

    train_transform: 
      - class_path: albumentations.HorizontalFlip
        init_args:
          p: 0.5
      - class_path: albumentations.VerticalFlip
        init_args:
          p: 0.5
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: albumentations.pytorch.ToTensorV2
    
    val_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: albumentations.pytorch.ToTensorV2

    test_transform:
      - class_path: albumentations.Resize
        init_args:
          height: 224
          width: 224
      - class_path: albumentations.pytorch.ToTensorV2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: prithvi_eo_v2_tiny_tl
      backbone_pretrained: true
      backbone_num_frames: 1
      backbone_bands: ["BLUE", "GREEN", "RED"]
            
      necks:
        - name: SelectIndices
          indices: [3, 5, 7, 11]
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal

      decoder: UNetDecoder
      decoder_channels: [512, 256, 128, 64]

      head_dropout: 0.1
      num_classes: 6

    loss: ce
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false
    class_names: ["Building", "Unpaved Area", "Road", "Vegetation", "Water", "Unlabeled"]

optimizer:
  class_path: torch.optim.AdamW 
  init_args:
    lr: 1e-4
    weight_decay: 0.05

trainer:
  accelerator: cuda
  devices: 1
  precision: 16-mixed
  max_epochs: 5
  default_root_dir: /content/demo/